site_name: Andrew Klein Website
site_description: Andrew Kleins website
site_author: Andrew Klein
site_url: https://github-andrewjordank.github.io/

# Repository
repo_name: Andrew_Klein_Website
repo_url: https://github.com/andrewjordank/Andrew_Klein_Website
edit_uri: edit/main/docs/
                        /Projects/
                        /Figures/

# Copyright
copyright: 'Copyright &copy; 2023 - 2024 Andrew Klein'


# Configuration
theme:
  name: material
  highlighjs: true
  font:
    text: Roboto
    code: Regular

  # Features  
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.indexes
  - navigation.top
  - toc.follow

  # 404 page
  static_templates:
    - 404.html

  # Search feature
  include_search_page: false
  search_index_only: true

  # Palette and theme (uses personalized colours)
  language: en
  palette:
    primary: amber
    accent: white
  icon:
    logo: material/cogs
  favicon: material/cogs

# Page tree
nav:
  - Home: index.md
  - About Me: 
      Personal Info: personal.md
      Resume: Andrew Klein_CV (1).pdf
  - Projects:
      Introduction: intro.md
      ABO Systematic Review: formulating_LD_plots-Andrew_Klein.md
      Heparin Induced Thrombocytopenia: intro.md
  - Codebase: 
      Installation and Requirements: requirements.txt
      User Manual: manual.md
  - Data Management Plan: Data_Management_Plan.md

# Theme Extras
extra_css:
  - stylesheets/extra.css

# Extra Plugins
plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True

# Extensions (leave as is)
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
